# generated by datamodel-codegen:
#   filename:  application_schema.yaml
#   timestamp: 2024-03-14T14:54:14+00:00

from __future__ import annotations

from datetime import date
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, RootModel


class Link(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    url: AnyUrl


class Settings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    application: str
    team: str


class DateTitleLinksComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date
    title: str
    links: List[Link]


class DateTitleLinks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    components: List[DateTitleLinksComponent]


class Activities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_title_link: Optional[DateTitleLinks] = None


class DSOMMapplication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: str = '1'
    kind: str = 'application'
    settings: Settings
    activities: Activities


class Model(RootModel[DSOMMapplication]):
    root: DSOMMapplication
