# generated by datamodel-codegen:
#   filename:  application_schema.yaml
#   timestamp: 2024-03-12T19:55:46+00:00

from __future__ import annotations

from datetime import date
from typing import List

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Link(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    url: AnyUrl


class ReductionOfTheAttackSurfaceComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date


class SourceControlProtectionComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl
    date: AwareDatetime


class Settings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    desired_level: str = Field(..., alias='desired level')
    application: str
    team: str


class ConductionOfSimpleThreatModelingOnTechnicalLevelComponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date
    title: str
    links: List[Link]


class ReductionOfTheAttackSurface(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    components: List[ReductionOfTheAttackSurfaceComponent]


class SourceControlProtection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    components: List[SourceControlProtectionComponent]


class ConductionOfSimpleThreatModelingOnTechnicalLevel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    components: List[ConductionOfSimpleThreatModelingOnTechnicalLevelComponent]


class Activities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Source_Control_Protection: SourceControlProtection = Field(
        ..., alias='Source Control Protection'
    )
    Conduction_of_simple_threat_modeling_on_technical_level: (
        ConductionOfSimpleThreatModelingOnTechnicalLevel
    ) = Field(..., alias='Conduction of simple threat modeling on technical level')
    Reduction_of_the_attack_surface: ReductionOfTheAttackSurface = Field(
        ..., alias='Reduction of the attack surface'
    )


class DSOMMapplication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    apiVersion: str
    kind: str
    settings: Settings
    activities: Activities


class Model(RootModel[DSOMMapplication]):
    root: DSOMMapplication
