{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/DSOMMapplication",
  "definitions": {
    "DSOMMapplication": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "apiVersion": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "settings": {
          "$ref": "#/definitions/Settings"
        },
        "activities": {
          "$ref": "#/definitions/Activities"
        }
      },
      "required": [
        "activities",
        "apiVersion",
        "kind",
        "settings"
      ],
      "title": "DSOMMapplication"
    },
    "Activities": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Source Control Protection": {
          "$ref": "#/definitions/SourceControlProtection"
        },
        "Conduction of simple threat modeling on technical level": {
          "$ref": "#/definitions/ConductionOfSimpleThreatModelingOnTechnicalLevel"
        },
        "Reduction of the attack surface": {
          "$ref": "#/definitions/ReductionOfTheAttackSurface"
        }
      },
      "required": [
        "Conduction of simple threat modeling on technical level",
        "Reduction of the attack surface",
        "Source Control Protection"
      ],
      "title": "Activities"
    },
    "ConductionOfSimpleThreatModelingOnTechnicalLevel": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "components": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ConductionOfSimpleThreatModelingOnTechnicalLevelComponent"
          }
        }
      },
      "required": [
        "components"
      ],
      "title": "ConductionOfSimpleThreatModelingOnTechnicalLevel"
    },
    "ConductionOfSimpleThreatModelingOnTechnicalLevelComponent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "title": {
          "type": "string"
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Link"
          }
        }
      },
      "required": [
        "date",
        "links",
        "title"
      ],
      "title": "ConductionOfSimpleThreatModelingOnTechnicalLevelComponent"
    },
    "Link": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        }
      },
      "required": [
        "title",
        "url"
      ],
      "title": "Link"
    },
    "ReductionOfTheAttackSurface": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "components": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ReductionOfTheAttackSurfaceComponent"
          }
        }
      },
      "required": [
        "components"
      ],
      "title": "ReductionOfTheAttackSurface"
    },
    "ReductionOfTheAttackSurfaceComponent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        }
      },
      "required": [
        "date"
      ],
      "title": "ReductionOfTheAttackSurfaceComponent"
    },
    "SourceControlProtection": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "components": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SourceControlProtectionComponent"
          }
        }
      },
      "required": [
        "components"
      ],
      "title": "SourceControlProtection"
    },
    "SourceControlProtectionComponent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "url": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        },
        "date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "date",
        "url"
      ],
      "title": "SourceControlProtectionComponent"
    },
    "Settings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "desired level": {
          "type": "string"
        },
        "application": {
          "type": "string"
        },
        "team": {
          "type": "string"
        }
      },
      "required": [
        "application",
        "desired level",
        "team"
      ],
      "title": "Settings"
    }
  }
}
