name: Demo scheduled Run of the Collector

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        env: 
          CONFLUENCE_URL: 'https://pagel-team-xbbaqjrbqjmj.atlassian.net/wiki'
          CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          GIT_HUB_ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          GIT_HUB_REPO: 'metricca-data'
          GIT_HUB_OWNER: 'devsecopsmaturitymodel'
        run: |
          echo $CONFLUENCE_URL
          pip install -r requirements.txt
          python3 ./confluence_collector.py scraping_config.yaml
